# Generated by Django 4.2.28 on 2026-02-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_id', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=20)),
            ],
        ),
    ]
