# Generated by Django 4.2.28 on 2026-02-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
