# Generated by Django 4.2.28 on 2026-03-02 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_inventoryitem_date_acquired_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(max_length=10)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('has_name_input', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=False)),
                ('inventory_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='inventory.inventorytype')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=True)),
                ('parent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='inventory.inventorytype')),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorytype')),
            ],
        ),
    ]
