# Generated by Django 4.2.28 on 2026-03-02 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventorytype_property_profile_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='category',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorytype'),
        ),
    ]
