# Generated by Django 4.2.28 on 2026-03-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_inventoryitem_category_inventoryitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='has_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='is_serial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='default_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
