# Generated by Django 4.2.28 on 2026-03-03 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_part_has_name_part_is_serial_property_default_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_parts', to='inventory.inventoryitem'),
        ),
    ]
