# Generated by Django 4.2.28 on 2026-02-28 05:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('office_name', models.CharField(max_length=100)),
                ('receiving_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrintingTicket',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.ticket')),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('width', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('quantity', models.IntegerField()),
                ('file_link', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField()),
            ],
            bases=('tickets.ticket',),
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.ticket')),
                ('device_name', models.CharField(max_length=100)),
                ('issue', models.TextField(max_length=255)),
                ('solution', models.TextField(max_length=255)),
            ],
            bases=('tickets.ticket',),
        ),
    ]
