# Generated by Django 4.2.28 on 2026-02-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='printingticket',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='printingticket',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='printingticket',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
