# Generated by Django 4.2.28 on 2026-02-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_user_name_ticket_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingticket',
            name='status',
            field=models.CharField(choices=[('for_approval', 'For Approval'), ('pending', 'Pending'), ('ongoing', 'Ongoing'), ('printed', 'Printed'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('for_approval', 'For Approval'), ('pending', 'Pending'), ('ongoing', 'Ongoing'), ('resolved', 'Resolved'), ('unrepairable', 'Unrepairable'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
