# Generated by Django 4.2.28 on 2026-03-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_printingticket_status_supportticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingticket',
            name='title',
            field=models.CharField(default='n/a', max_length=100),
        ),
    ]
