# Generated by Django 4.2.28 on 2026-03-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_printingticket_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingticket',
            name='file_link',
            field=models.CharField(default='n/a', max_length=100),
        ),
    ]
