# Generated by Django 4.2.28 on 2026-03-02 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_printingticket_file_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportticket',
            old_name='device_name',
            new_name='item_name',
        ),
    ]
