# Generated by Django 4.2.28 on 2026-03-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_rename_device_name_supportticket_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='device_id',
            field=models.CharField(default='0', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printingticket',
            name='deadline',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
